### ISSUE TITLE
Integrieren in bestehende Strukturen

### ISSUE THREAD

**Issue by Matthias84** [lambdahro/organisation#1]
Ich bin nicht sicher, ob das einen issue wert ist, aber ich denke es ist sinnvoll, wenn ihr euch auch noch in den existierenden bestehenden Strukturen in Rostock einklinkt:

* www.hack-hro.de
* www.stadtgestalten.de
* https://www.lohro.de/programm/sendungen/words-for-nerds/
* https://www.fsr-inf.uni-rostock.de

Sicherlich gibt es dort Neugierige, die noch nichts von eurem Projekt gehört haben und euch evtl. unterstützen können :+1:

**Comment by jan0sch** [comment]
Danke für die Infos. :)

**Comment by jan0sch** [comment]
- [ ] Hack-HRO
- [ ] Lohro
- [x] FSR Informatik
- [x] stadtgestalten.org
